/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#ifndef CLASS_Engine_Asset
#define CLASS_Engine_Asset

/* Imports */
class Object;
namespace Engine { class InternalConstructorOnlyException; } 
#include "Object.h"
#include "Enumerations.h"

/* Using declarations */

namespace Engine
{
    /* Begin class declaration */
    class Asset : public Object
    {
        /* Variable declarations */
        private: std::string m_Name;

        /* Method and constructor declarations */
        public: Asset(lua_State * L, bool byuser);

        /* Automatic dispatchers for overloaded methods */

        /* Automatic property getter-setter declarations */

        /* Binding variables */
        public: static const char *ClassName;
        public: static const char *Inherits;
        public: static const Bindings<Asset>::FunctionType Functions[];
        public: static const Bindings<Asset>::PropertyType Properties[];
        public: static int (__cdecl *Dispatcher)(lua_State * L);
    };
} 

#endif

