/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#ifndef CLASS_Engine_Exception
#define CLASS_Engine_Exception

/* Imports */
class Object;
#include "Object.h"
#include <string>
#include <sstream>
#include <vector>
#include "Utility.h"
#include "Program.h"
#include "StackPoint.h"

/* Using declarations */

namespace Engine
{
    /* Begin class declaration */
    class Exception : public Object
    {
        /* Variable declarations */
        public: static const char* Message;
        public: int  LineNumber;
        public: std::string FileName;
        public: std::vector<std::string> Arguments;
        public: std::vector<Monocle::CallStackPoint> CallStackTrace;
        public: std::vector<Monocle::DataStackPoint> DataStackTrace;

        /* Method and constructor declarations */
        public: Exception();
        public: Exception(lua_State * L, bool byuser);
        private: void GatherEnvironmentData(lua_State * L);
        public: static std::string GetParsedMessage(std::string msg, std::vector<std::string> args);
        public: virtual const char* GetMessage();
        public: virtual const char* GetName();
        private: int GetMessageL(lua_State * L);

        /* Automatic dispatchers for overloaded methods */

        /* Automatic property getter-setter declarations */

        /* Binding variables */
        public: static const char *ClassName;
        public: static const char *Inherits;
        public: static const Bindings<Exception>::FunctionType Functions[];
        public: static const Bindings<Exception>::PropertyType Properties[];
        public: static int (__cdecl *Dispatcher)(lua_State * L);
    };
} 

#endif

