/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#ifndef CLASS_Engine_Graphics
#define CLASS_Engine_Graphics

/* Imports */
class Object;
namespace Engine { class InternalConstructorOnlyException; } 
#include "Object.h"

/* Using declarations */

namespace Engine
{
    /* Begin class declaration */
    class Graphics : public Object
    {
        /* Variable declarations */

        /* Method and constructor declarations */
        public: Graphics(lua_State * L, bool byuser);
        public: Graphics();
        public: void BeginFrame();
        public: void EndFrame();
        public: void ShowBuffer();

        /* Automatic dispatchers for overloaded methods */

        /* Automatic property getter-setter declarations */

        /* Binding variables */
        public: static const char *ClassName;
        public: static const char *Inherits;
        public: static const Bindings<Graphics>::FunctionType Functions[];
        public: static const Bindings<Graphics>::PropertyType Properties[];
        public: static int (__cdecl *Dispatcher)(lua_State * L);
    };
} 

#endif

