/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "AccessViolationException.h"

namespace Engine
{
    /* Variable assignments */
    const char* AccessViolationException::Message = "The operation resulted in an access violation occurring within native code.";

    /* Method and constructor definitions */
    AccessViolationException::AccessViolationException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    AccessViolationException::AccessViolationException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* AccessViolationException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* AccessViolationException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int AccessViolationException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* AccessViolationException::ClassName = "Engine.AccessViolationException";
    const char* AccessViolationException::Inherits = "Engine.LowLevelException";
    const Bindings<AccessViolationException>::FunctionType AccessViolationException::Functions[] =
    {
        {0}
    };
    const Bindings<AccessViolationException>::PropertyType AccessViolationException::Properties[] =
    {
        {"Message", &AccessViolationException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *AccessViolationException::Dispatcher)(lua_State * L) = &(Bindings<AccessViolationException>::FunctionDispatch);
} 

