/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "ArgumentCountMismatchException.h"
#include <vector>
#include <string>
#include <sstream>

namespace Engine
{
    /* Variable assignments */
    const char* ArgumentCountMismatchException::Message = "The number of arguments passed to the function is not valid.";

    /* Method and constructor definitions */
    ArgumentCountMismatchException::ArgumentCountMismatchException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    ArgumentCountMismatchException::ArgumentCountMismatchException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* ArgumentCountMismatchException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* ArgumentCountMismatchException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int ArgumentCountMismatchException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* ArgumentCountMismatchException::ClassName = "Engine.ArgumentCountMismatchException";
    const char* ArgumentCountMismatchException::Inherits = "Engine.InterpreterException";
    const Bindings<ArgumentCountMismatchException>::FunctionType ArgumentCountMismatchException::Functions[] =
    {
        {0}
    };
    const Bindings<ArgumentCountMismatchException>::PropertyType ArgumentCountMismatchException::Properties[] =
    {
        {"Message", &ArgumentCountMismatchException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *ArgumentCountMismatchException::Dispatcher)(lua_State * L) = &(Bindings<ArgumentCountMismatchException>::FunctionDispatch);
} 

