/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Asset.h"
#include "InternalConstructorOnlyException.h"
#include "Enumerations.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Asset::Asset(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Asset::ClassName = "Engine.Asset";
    const char* Asset::Inherits = "Object";
    const Bindings<Asset>::FunctionType Asset::Functions[] =
    {
        {0}
    };
    const Bindings<Asset>::PropertyType Asset::Properties[] =
    {
        {0}
    };
    int (__cdecl *Asset::Dispatcher)(lua_State * L) = &(Bindings<Asset>::FunctionDispatch);
} 

