/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "ContextNotProvidedException.h"

namespace Engine
{
    /* Variable assignments */
    const char* ContextNotProvidedException::Message = "There was no context for this function provided.  Ensure that you use the ':' operator on member functions.";

    /* Method and constructor definitions */
    ContextNotProvidedException::ContextNotProvidedException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    ContextNotProvidedException::ContextNotProvidedException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* ContextNotProvidedException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* ContextNotProvidedException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
    int ContextNotProvidedException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    int ContextNotProvidedException::SetMessageL(lua_State * L)
    {
        ::string value = Bindings<::string>::GetArgumentBase(L, -1);

        throw new Engine::ReadOnlyPropertyException();
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* ContextNotProvidedException::ClassName = "Engine.ContextNotProvidedException";
    const char* ContextNotProvidedException::Inherits = "Engine.EngineException";
    const Bindings<ContextNotProvidedException>::FunctionType ContextNotProvidedException::Functions[] =
    {
        {0}
    };
    const Bindings<ContextNotProvidedException>::PropertyType ContextNotProvidedException::Properties[] =
    {
        {"Message", &ContextNotProvidedException::GetMessageL, &ContextNotProvidedException::SetMessageL},
        {0}
    };
    int (__cdecl *ContextNotProvidedException::Dispatcher)(lua_State * L) = &(Bindings<ContextNotProvidedException>::FunctionDispatch);
} 

