/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Core.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Core::Core(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Core::ClassName = "Engine.Core";
    const char* Core::Inherits = "Object";
    const Bindings<Core>::FunctionType Core::Functions[] =
    {
        {0}
    };
    const Bindings<Core>::PropertyType Core::Properties[] =
    {
        {0}
    };
    int (__cdecl *Core::Dispatcher)(lua_State * L) = &(Bindings<Core>::FunctionDispatch);
} 

