/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "DataMisalignedException.h"

namespace Engine
{
    /* Variable assignments */
    const char* DataMisalignedException::Message = "A native data structure was not correctly aligned on memory boundaries when an operation was performed on it.";

    /* Method and constructor definitions */
    DataMisalignedException::DataMisalignedException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    DataMisalignedException::DataMisalignedException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* DataMisalignedException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* DataMisalignedException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int DataMisalignedException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* DataMisalignedException::ClassName = "Engine.DataMisalignedException";
    const char* DataMisalignedException::Inherits = "Engine.LowLevelException";
    const Bindings<DataMisalignedException>::FunctionType DataMisalignedException::Functions[] =
    {
        {0}
    };
    const Bindings<DataMisalignedException>::PropertyType DataMisalignedException::Properties[] =
    {
        {"Message", &DataMisalignedException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *DataMisalignedException::Dispatcher)(lua_State * L) = &(Bindings<DataMisalignedException>::FunctionDispatch);
} 

