/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "EntryPointNotFoundException.h"

namespace Engine
{
    /* Variable assignments */
    const char* EntryPointNotFoundException::Message = "The entry point for the game could not be found, due to the GameInfo.xml file missing or being invalid.";

    /* Method and constructor definitions */
    EntryPointNotFoundException::EntryPointNotFoundException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    EntryPointNotFoundException::EntryPointNotFoundException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* EntryPointNotFoundException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* EntryPointNotFoundException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int EntryPointNotFoundException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* EntryPointNotFoundException::ClassName = "Engine.EntryPointNotFoundException";
    const char* EntryPointNotFoundException::Inherits = "Engine.EngineException";
    const Bindings<EntryPointNotFoundException>::FunctionType EntryPointNotFoundException::Functions[] =
    {
        {0}
    };
    const Bindings<EntryPointNotFoundException>::PropertyType EntryPointNotFoundException::Properties[] =
    {
        {"Message", &EntryPointNotFoundException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *EntryPointNotFoundException::Dispatcher)(lua_State * L) = &(Bindings<EntryPointNotFoundException>::FunctionDispatch);
} 

