/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Graphics.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Graphics::Graphics(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Graphics::ClassName = "Engine.Graphics";
    const char* Graphics::Inherits = "Object";
    const Bindings<Graphics>::FunctionType Graphics::Functions[] =
    {
        {0}
    };
    const Bindings<Graphics>::PropertyType Graphics::Properties[] =
    {
        {0}
    };
    int (__cdecl *Graphics::Dispatcher)(lua_State * L) = &(Bindings<Graphics>::FunctionDispatch);
} 

