/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "GraphicsEngineNotFoundException.h"

namespace Engine
{
    /* Variable assignments */
    const char* GraphicsEngineNotFoundException::Message = "There is no suitable 3D graphics engine available on this machine.";

    /* Method and constructor definitions */
    GraphicsEngineNotFoundException::GraphicsEngineNotFoundException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    GraphicsEngineNotFoundException::GraphicsEngineNotFoundException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* GraphicsEngineNotFoundException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* GraphicsEngineNotFoundException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int GraphicsEngineNotFoundException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* GraphicsEngineNotFoundException::ClassName = "Engine.GraphicsEngineNotFoundException";
    const char* GraphicsEngineNotFoundException::Inherits = "Engine.EngineException";
    const Bindings<GraphicsEngineNotFoundException>::FunctionType GraphicsEngineNotFoundException::Functions[] =
    {
        {0}
    };
    const Bindings<GraphicsEngineNotFoundException>::PropertyType GraphicsEngineNotFoundException::Properties[] =
    {
        {"Message", &GraphicsEngineNotFoundException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *GraphicsEngineNotFoundException::Dispatcher)(lua_State * L) = &(Bindings<GraphicsEngineNotFoundException>::FunctionDispatch);
} 

