/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "IllegalInstructionException.h"

namespace Engine
{
    /* Variable assignments */
    const char* IllegalInstructionException::Message = "An illegal assembly operation was attempted within native code.  This indicates a bug in the compiler that produced the native code.";

    /* Method and constructor definitions */
    IllegalInstructionException::IllegalInstructionException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    IllegalInstructionException::IllegalInstructionException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* IllegalInstructionException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* IllegalInstructionException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int IllegalInstructionException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* IllegalInstructionException::ClassName = "Engine.IllegalInstructionException";
    const char* IllegalInstructionException::Inherits = "Engine.LowLevelException";
    const Bindings<IllegalInstructionException>::FunctionType IllegalInstructionException::Functions[] =
    {
        {0}
    };
    const Bindings<IllegalInstructionException>::PropertyType IllegalInstructionException::Properties[] =
    {
        {"Message", &IllegalInstructionException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *IllegalInstructionException::Dispatcher)(lua_State * L) = &(Bindings<IllegalInstructionException>::FunctionDispatch);
} 

