/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "InheritedClassNotFoundException.h"

namespace Engine
{
    /* Variable assignments */
    const char* InheritedClassNotFoundException::Message = "The __type metamethod was called on a native object that has a parent class, but the parent class is not yet available in Lua for reference.";

    /* Method and constructor definitions */
    InheritedClassNotFoundException::InheritedClassNotFoundException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    InheritedClassNotFoundException::InheritedClassNotFoundException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* InheritedClassNotFoundException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* InheritedClassNotFoundException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int InheritedClassNotFoundException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* InheritedClassNotFoundException::ClassName = "Engine.InheritedClassNotFoundException";
    const char* InheritedClassNotFoundException::Inherits = "Engine.EngineException";
    const Bindings<InheritedClassNotFoundException>::FunctionType InheritedClassNotFoundException::Functions[] =
    {
        {0}
    };
    const Bindings<InheritedClassNotFoundException>::PropertyType InheritedClassNotFoundException::Properties[] =
    {
        {"Message", &InheritedClassNotFoundException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *InheritedClassNotFoundException::Dispatcher)(lua_State * L) = &(Bindings<InheritedClassNotFoundException>::FunctionDispatch);
} 

