/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Input.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Input::Input(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Input::ClassName = "Engine.Input";
    const char* Input::Inherits = "Object";
    const Bindings<Input>::FunctionType Input::Functions[] =
    {
        {0}
    };
    const Bindings<Input>::PropertyType Input::Properties[] =
    {
        {0}
    };
    int (__cdecl *Input::Dispatcher)(lua_State * L) = &(Bindings<Input>::FunctionDispatch);
} 

