/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "InterpreterStateNotValidException.h"

namespace Engine
{
    /* Variable assignments */
    const char* InterpreterStateNotValidException::Message = "The Lua interpreter is in an invalid state or could otherwise not be initalized correctly.";

    /* Method and constructor definitions */
    InterpreterStateNotValidException::InterpreterStateNotValidException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    InterpreterStateNotValidException::InterpreterStateNotValidException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* InterpreterStateNotValidException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* InterpreterStateNotValidException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int InterpreterStateNotValidException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* InterpreterStateNotValidException::ClassName = "Engine.InterpreterStateNotValidException";
    const char* InterpreterStateNotValidException::Inherits = "Engine.InterpreterException";
    const Bindings<InterpreterStateNotValidException>::FunctionType InterpreterStateNotValidException::Functions[] =
    {
        {0}
    };
    const Bindings<InterpreterStateNotValidException>::PropertyType InterpreterStateNotValidException::Properties[] =
    {
        {"Message", &InterpreterStateNotValidException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *InterpreterStateNotValidException::Dispatcher)(lua_State * L) = &(Bindings<InterpreterStateNotValidException>::FunctionDispatch);
} 

