/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */
    const char* InternalConstructorOnlyException::Message = "Attempted to construct an object whose constructor is for internal use only.";

    /* Method and constructor definitions */
    InternalConstructorOnlyException::InternalConstructorOnlyException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    InternalConstructorOnlyException::InternalConstructorOnlyException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* InternalConstructorOnlyException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* InternalConstructorOnlyException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int InternalConstructorOnlyException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* InternalConstructorOnlyException::ClassName = "Engine.InternalConstructorOnlyException";
    const char* InternalConstructorOnlyException::Inherits = "Engine.EngineException";
    const Bindings<InternalConstructorOnlyException>::FunctionType InternalConstructorOnlyException::Functions[] =
    {
        {0}
    };
    const Bindings<InternalConstructorOnlyException>::PropertyType InternalConstructorOnlyException::Properties[] =
    {
        {"Message", &InternalConstructorOnlyException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *InternalConstructorOnlyException::Dispatcher)(lua_State * L) = &(Bindings<InternalConstructorOnlyException>::FunctionDispatch);
} 

