/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "InvalidOperationException.h"

namespace Engine
{
    /* Variable assignments */
    const char* InvalidOperationException::Message = "An operation was attempted that is not valid for the current state.";

    /* Method and constructor definitions */
    InvalidOperationException::InvalidOperationException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    InvalidOperationException::InvalidOperationException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* InvalidOperationException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* InvalidOperationException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int InvalidOperationException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* InvalidOperationException::ClassName = "Engine.InvalidOperationException";
    const char* InvalidOperationException::Inherits = "Engine.InterpreterException";
    const Bindings<InvalidOperationException>::FunctionType InvalidOperationException::Functions[] =
    {
        {0}
    };
    const Bindings<InvalidOperationException>::PropertyType InvalidOperationException::Properties[] =
    {
        {"Message", &InvalidOperationException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *InvalidOperationException::Dispatcher)(lua_State * L) = &(Bindings<InvalidOperationException>::FunctionDispatch);
} 

