/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "KeyNotFoundException.h"

namespace Engine
{
    /* Variable assignments */
    const char* KeyNotFoundException::Message = "Attempted to index a key which does not exist in the table.";

    /* Method and constructor definitions */
    KeyNotFoundException::KeyNotFoundException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    KeyNotFoundException::KeyNotFoundException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* KeyNotFoundException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* KeyNotFoundException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int KeyNotFoundException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* KeyNotFoundException::ClassName = "Engine.KeyNotFoundException";
    const char* KeyNotFoundException::Inherits = "Engine.InterpreterException";
    const Bindings<KeyNotFoundException>::FunctionType KeyNotFoundException::Functions[] =
    {
        {0}
    };
    const Bindings<KeyNotFoundException>::PropertyType KeyNotFoundException::Properties[] =
    {
        {"Message", &KeyNotFoundException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *KeyNotFoundException::Dispatcher)(lua_State * L) = &(Bindings<KeyNotFoundException>::FunctionDispatch);
} 

