/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "LowLevelException.h"

namespace Engine
{
    /* Variable assignments */
    const char* LowLevelException::Message = "A general exception was raised within native code.";

    /* Method and constructor definitions */
    LowLevelException::LowLevelException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    LowLevelException::LowLevelException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* LowLevelException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* LowLevelException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int LowLevelException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* LowLevelException::ClassName = "Engine.LowLevelException";
    const char* LowLevelException::Inherits = "Engine.Exception";
    const Bindings<LowLevelException>::FunctionType LowLevelException::Functions[] =
    {
        {0}
    };
    const Bindings<LowLevelException>::PropertyType LowLevelException::Properties[] =
    {
        {"Message", &LowLevelException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *LowLevelException::Dispatcher)(lua_State * L) = &(Bindings<LowLevelException>::FunctionDispatch);
} 

