/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "OutOfMemoryException.h"

namespace Engine
{
    /* Variable assignments */
    const char* OutOfMemoryException::Message = "There was not enough memory to perform the operation.";

    /* Method and constructor definitions */
    OutOfMemoryException::OutOfMemoryException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    OutOfMemoryException::OutOfMemoryException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* OutOfMemoryException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* OutOfMemoryException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int OutOfMemoryException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* OutOfMemoryException::ClassName = "Engine.OutOfMemoryException";
    const char* OutOfMemoryException::Inherits = "Engine.LowLevelException";
    const Bindings<OutOfMemoryException>::FunctionType OutOfMemoryException::Functions[] =
    {
        {0}
    };
    const Bindings<OutOfMemoryException>::PropertyType OutOfMemoryException::Properties[] =
    {
        {"Message", &OutOfMemoryException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *OutOfMemoryException::Dispatcher)(lua_State * L) = &(Bindings<OutOfMemoryException>::FunctionDispatch);
} 

