/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "OverflowException.h"

namespace Engine
{
    /* Variable assignments */
    const char* OverflowException::Message = "An integer or floating point overflow occurred within native code.";

    /* Method and constructor definitions */
    OverflowException::OverflowException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    OverflowException::OverflowException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* OverflowException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* OverflowException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int OverflowException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* OverflowException::ClassName = "Engine.OverflowException";
    const char* OverflowException::Inherits = "Engine.LowLevelException";
    const Bindings<OverflowException>::FunctionType OverflowException::Functions[] =
    {
        {0}
    };
    const Bindings<OverflowException>::PropertyType OverflowException::Properties[] =
    {
        {"Message", &OverflowException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *OverflowException::Dispatcher)(lua_State * L) = &(Bindings<OverflowException>::FunctionDispatch);
} 

