/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "PathNotFoundException.h"

namespace Engine
{
    /* Variable assignments */
    const char* PathNotFoundException::Message = "The specified path '${1}' could not be found.";

    /* Method and constructor definitions */
    PathNotFoundException::PathNotFoundException(std::string path)
    {
        this->Arguments.insert(this->Arguments.end(), path);
	}

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    PathNotFoundException::PathNotFoundException(lua_State * L, bool byuser)
    {
        ::string path = Bindings<::string>::GetArgumentBase(L, 1);

        this->Arguments.insert(this->Arguments.end(), path);
	}

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* PathNotFoundException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* PathNotFoundException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int PathNotFoundException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* PathNotFoundException::ClassName = "Engine.PathNotFoundException";
    const char* PathNotFoundException::Inherits = "Engine.EngineException";
    const Bindings<PathNotFoundException>::FunctionType PathNotFoundException::Functions[] =
    {
        {0}
    };
    const Bindings<PathNotFoundException>::PropertyType PathNotFoundException::Properties[] =
    {
        {"Message", &PathNotFoundException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *PathNotFoundException::Dispatcher)(lua_State * L) = &(Bindings<PathNotFoundException>::FunctionDispatch);
} 

