/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Platform.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Platform::Platform(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Platform::ClassName = "Engine.Platform";
    const char* Platform::Inherits = "Object";
    const Bindings<Platform>::FunctionType Platform::Functions[] =
    {
        {0}
    };
    const Bindings<Platform>::PropertyType Platform::Properties[] =
    {
        {0}
    };
    int (__cdecl *Platform::Dispatcher)(lua_State * L) = &(Bindings<Platform>::FunctionDispatch);
} 

