/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "ReadOnlyPropertyException.h"

namespace Engine
{
    /* Variable assignments */
    const char* ReadOnlyPropertyException::Message = "The specified property is read-only.";

    /* Method and constructor definitions */
    ReadOnlyPropertyException::ReadOnlyPropertyException()
    {
        }

	/// <summary>
	/// Exception constructor for Lua code.
	/// </summary>
    ReadOnlyPropertyException::ReadOnlyPropertyException(lua_State * L, bool byuser)
    {
        }

	/// <summary>
	/// Returns the static Message variable.  Required for downcasting.
	/// <summary>
    const char* ReadOnlyPropertyException::GetMessage()
    {
        return this->Message;
	}

	/// <summary>
	/// Returns the static ClassName variable.  Required for downcasting.
	/// <summary>
    const char* ReadOnlyPropertyException::GetName()
    {
        return this->ClassName;
	}

	/// <summary>
	/// A property to access the exception message.
	/// </summary>
	/// <readonly>true</readonly>
    int ReadOnlyPropertyException::GetMessageL(lua_State * L)
    {

        return Bindings<::string>::Result(L, Engine::Exception::GetParsedMessage(this->Message, this->Arguments).c_str());
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* ReadOnlyPropertyException::ClassName = "Engine.ReadOnlyPropertyException";
    const char* ReadOnlyPropertyException::Inherits = "Engine.EngineException";
    const Bindings<ReadOnlyPropertyException>::FunctionType ReadOnlyPropertyException::Functions[] =
    {
        {0}
    };
    const Bindings<ReadOnlyPropertyException>::PropertyType ReadOnlyPropertyException::Properties[] =
    {
        {"Message", &ReadOnlyPropertyException::GetMessageL, NULL},
        {0}
    };
    int (__cdecl *ReadOnlyPropertyException::Dispatcher)(lua_State * L) = &(Bindings<ReadOnlyPropertyException>::FunctionDispatch);
} 

