/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "TextureAsset.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    TextureAsset::TextureAsset(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* TextureAsset::ClassName = "Engine.TextureAsset";
    const char* TextureAsset::Inherits = "Object";
    const Bindings<TextureAsset>::FunctionType TextureAsset::Functions[] =
    {
        {0}
    };
    const Bindings<TextureAsset>::PropertyType TextureAsset::Properties[] =
    {
        {0}
    };
    int (__cdecl *TextureAsset::Dispatcher)(lua_State * L) = &(Bindings<TextureAsset>::FunctionDispatch);
} 

