/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Vector2.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Vector2::Vector2(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Vector2::ClassName = "Engine.Vector2";
    const char* Vector2::Inherits = "Object";
    const Bindings<Vector2>::FunctionType Vector2::Functions[] =
    {
        {0}
    };
    const Bindings<Vector2>::PropertyType Vector2::Properties[] =
    {
        {0}
    };
    int (__cdecl *Vector2::Dispatcher)(lua_State * L) = &(Bindings<Vector2>::FunctionDispatch);
} 

