/*
 * This file was automatically generated by AutoBind.
 * Any changes made to this file will be lost when it
 * is next regenerated.
 */

#include "autobind/types.h"
#include "autobind/binding/lua.h"
#include "Object.h"
#include "Vector3.h"
#include "InternalConstructorOnlyException.h"

namespace Engine
{
    /* Variable assignments */

    /* Method and constructor definitions */
    Vector3::Vector3(lua_State * L, bool byuser)
    {
        if (byuser)
		{
			throw new Engine::InternalConstructorOnlyException();
		}
		// TODO: Implement.
	}

    /* Automatic dispatchers for overloaded methods */
    /* Automatic property getter-setter definitions */
    /* Binding variables */
    const char* Vector3::ClassName = "Engine.Vector3";
    const char* Vector3::Inherits = "Object";
    const Bindings<Vector3>::FunctionType Vector3::Functions[] =
    {
        {0}
    };
    const Bindings<Vector3>::PropertyType Vector3::Properties[] =
    {
        {0}
    };
    int (__cdecl *Vector3::Dispatcher)(lua_State * L) = &(Bindings<Vector3>::FunctionDispatch);
} 

