//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBind {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class CompileErrorList : global::System.Configuration.ApplicationSettingsBase {
        
        private static CompileErrorList defaultInstance = ((CompileErrorList)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CompileErrorList())));
        
        public static CompileErrorList Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to locate AutoBind.xml within the current working directory.")]
        public string A0001 {
            get {
                return ((string)(this["A0001"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to locate the input folder \'${1}\'.")]
        public string A0002 {
            get {
                return ((string)(this["A0002"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to locate the header output folder \'${1}\'.")]
        public string A0003 {
            get {
                return ((string)(this["A0003"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unable to locate the code output folder \'${1}\'.")]
        public string A0004 {
            get {
                return ((string)(this["A0004"]));
            }
        }
    }
}
